// WireGuard peer provisioning.
//
// Manages peers by shelling out to the `wg` CLI.
// Each paying agent gets a unique keypair and a /32 IP from 10.0.0.10–10.0.0.209.
//
// NOTE (Day 2): addPeer / removePeer calls must be serialised with an async
// queue to prevent race conditions under concurrent payments — see TODOS.md.

import { execFileSync } from 'node:child_process';
import { buildConfig } from '../config.js';
import { logger } from '../logger.js';
import { redis } from './redis.js';
import { storeSession, getSession, deleteSession } from './session.js';

const config = buildConfig();

const IP_COUNTER_KEY = 'tollgate:wg_ip_counter';

export interface Keypair {
  privateKey: string;
  publicKey: string;
}

export interface ProvisionResult {
  wireGuardConfig: string;
  allowedIP: string;
  sessionId: string;
}

// ─── Keypair ──────────────────────────────────────────────────────────────────

export function generateKeypair(): Keypair {
  const privateKey = execFileSync('wg', ['genkey']).toString().trim();
  const publicKey  = execFileSync('wg', ['pubkey'], { input: privateKey }).toString().trim();
  return { privateKey, publicKey };
}

// ─── IP allocation ────────────────────────────────────────────────────────────

// Atomically increments a Redis counter and maps it to 10.0.0.10–10.0.0.209.
// Stays clear of .0 (network), .1 (server gateway), and .255 (broadcast).
export async function allocateIP(): Promise<string> {
  const counter = await redis.incr(IP_COUNTER_KEY);
  const octet   = (counter % 200) + 10;   // 10 – 209
  return `10.0.0.${octet}`;
}

// ─── Peer management ─────────────────────────────────────────────────────────

export async function addPeer(publicKey: string, allowedIP: string): Promise<boolean> {
  execFileSync('wg', ['set', config.WG_INTERFACE, 'peer', publicKey, 'allowed-ips', `${allowedIP}/32`]);
  return true;
}

export async function removePeer(publicKey: string): Promise<boolean> {
  try {
    execFileSync('wg', ['set', config.WG_INTERFACE, 'peer', publicKey, 'remove']);
    return true;
  } catch (err) {
    // Peer may have already been removed — log but don't throw
    logger.warn({ err }, '[wireguard] removePeer failed (peer may already be gone)');
    return false;
  }
}

// ─── Client config builder ────────────────────────────────────────────────────

export function buildClientConfig(privateKey: string, allowedIP: string): string {
  if (!config.WG_SERVER_PUBLIC_KEY) throw new Error('WG_SERVER_PUBLIC_KEY not set in env');
  if (!config.WG_SERVER_ENDPOINT)   throw new Error('WG_SERVER_ENDPOINT not set in env');

  return [
    '[Interface]',
    `PrivateKey = ${privateKey}`,
    `Address = ${allowedIP}/32`,
    `DNS = ${config.WG_DNS}`,
    '',
    '[Peer]',
    `PublicKey = ${config.WG_SERVER_PUBLIC_KEY}`,
    `Endpoint = ${config.WG_SERVER_ENDPOINT}:${config.WG_SERVER_PORT}`,
    'AllowedIPs = 0.0.0.0/0, ::/0',
    'PersistentKeepalive = 25',
  ].join('\n');
}

// ─── Orchestration ────────────────────────────────────────────────────────────

/**
 * Full peer provisioning flow for a verified payment.
 * @param sessionId - UUID generated by the route handler
 */
export async function provisionPeer(sessionId: string): Promise<ProvisionResult> {
  // Stub mode: used during testing on machines without WireGuard installed.
  if (process.env.WG_STUB === 'true') {
    return {
      wireGuardConfig: '[Interface]\nPrivateKey = stub\nAddress = 10.0.0.10/32\n\n[Peer]\nPublicKey = stub',
      allowedIP: '10.0.0.10',
      sessionId,
    };
  }

  const { privateKey, publicKey } = generateKeypair();
  const allowedIP                 = await allocateIP();

  await addPeer(publicKey, allowedIP);

  const wireGuardConfig = buildClientConfig(privateKey, allowedIP);

  const stored = await storeSession(
    sessionId,
    { publicKey, allowedIP, wireGuardConfig },
    config.SESSION_TTL_SECONDS
  );

  if (!stored) {
    await removePeer(publicKey);
    throw new Error('Failed to persist session to Redis — peer not provisioned');
  }

  return { wireGuardConfig, allowedIP, sessionId };
}

/**
 * Remove a peer and clean up its session on TTL expiry or manual revocation.
 */
export async function expirePeer(sessionId: string): Promise<boolean> {
  const session = await getSession(sessionId);
  if (!session) {
    logger.warn({ sessionId }, '[wireguard] expirePeer: session not found');
    return false;
  }
  await removePeer(session.publicKey);
  await deleteSession(sessionId);
  return true;
}
